-- Create tables
CREATE TABLE CUSTOMER (
    CUST_ID SERIAL PRIMARY KEY,
    CUST_NAME VARCHAR(100) NOT NULL,
    CUST_GENDER INTEGER NOT NULL CHECK (CUST_GENDER IN (1, 2))
);

CREATE TABLE ACCOUNT (
    ACC_NUMBER VARCHAR(20) PRIMARY KEY,
    ACC_OWNER INTEGER NOT NULL,
    ACC_BALANCE DECIMAL(15, 2) NOT NULL,
    FOREIGN KEY (ACC_OWNER) REFERENCES CUSTOMER(CUST_ID)
);

CREATE TABLE TRANSACTION (
    TRS_ID SERIAL PRIMARY KEY,
    TRS_FROM_ACCOUNT VARCHAR(20) NOT NULL,
    TRS_DATE TIMESTAMP NOT NULL,
    TRS_AMOUNT DECIMAL(15, 2) NOT NULL,
    TRS_TYPE CHAR(2) NOT NULL CHECK (TRS_TYPE IN ('DB', 'CR', 'TF')),
    FOREIGN KEY (TRS_FROM_ACCOUNT) REFERENCES ACCOUNT(ACC_NUMBER)
);

CREATE TABLE TRANSACTION_TRANSFER (
    TRS_ID INTEGER PRIMARY KEY,
    TRS_TO_ACCOUNT VARCHAR(20) NOT NULL,
    TRS_STATUS INTEGER NOT NULL CHECK (TRS_STATUS IN (0, 1, -1)),
    FOREIGN KEY (TRS_ID) REFERENCES TRANSACTION(TRS_ID),
    FOREIGN KEY (TRS_TO_ACCOUNT) REFERENCES ACCOUNT(ACC_NUMBER)
);

-- CreateTable
CREATE TABLE "User" (
    "id" SERIAL NOT NULL,
    "username" TEXT NOT NULL,
    "password" TEXT NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_username_key" ON "User"("username");

-- Insert demo data
INSERT INTO CUSTOMER (CUST_NAME, CUST_GENDER) VALUES
('John Michael', 1),
('Jane Doe', 2),
('Robert Smith', 1);

INSERT INTO ACCOUNT (ACC_NUMBER, ACC_OWNER, ACC_BALANCE) VALUES
('1001', 1, 5000.00),
('1002', 1, 3000.00),
('2001', 2, 4500.00),
('3001', 3, 6000.00);

INSERT INTO TRANSACTION (TRS_FROM_ACCOUNT, TRS_DATE, TRS_AMOUNT, TRS_TYPE) VALUES
('1001', '2024-03-15 10:00:00', 500.00, 'DB'),
('1002', '2024-03-16 11:30:00', 200.00, 'CR'),
('1001', '2024-03-17 09:45:00', 1000.00, 'TF'),
('2001', '2024-03-18 14:20:00', 300.00, 'DB'),
('3001', '2024-03-19 16:00:00', 1500.00, 'TF');

INSERT INTO TRANSACTION_TRANSFER (TRS_ID, TRS_TO_ACCOUNT, TRS_STATUS) VALUES
(3, '2001', 1),
(5, '1002', 1);


-- question number 1
/*

SELECT 
    c.CUST_ID,
    c.CUST_NAME,
    COUNT(a.ACC_NUMBER) AS number_of_accounts
FROM 
    CUSTOMER c
LEFT JOIN 
    ACCOUNT a ON c.CUST_ID = a.ACC_OWNER
GROUP BY 
    c.CUST_ID, c.CUST_NAME
ORDER BY 
    c.CUST_ID;

*/

-- question number 2
/*
SELECT 
    t.TRS_ID,
    t.TRS_FROM_ACCOUNT,
    t.TRS_DATE,
    t.TRS_AMOUNT,
    t.TRS_TYPE
FROM 
    TRANSACTION t
JOIN 
    ACCOUNT a ON t.TRS_FROM_ACCOUNT = a.ACC_NUMBER
JOIN 
    CUSTOMER c ON a.ACC_OWNER = c.CUST_ID
WHERE 
    c.CUST_NAME = 'John Michael'
ORDER BY 
    t.TRS_FROM_ACCOUNT, t.TRS_DATE;
*/